### ISSUE TITLE
Store UUID as binary

### ISSUE THREAD

**Issue by londoh** [alsofronie/eloquent-uuid#1]
Hi

I was just searching for laravel uuid and came across your package.

According to my understanding when using UUID as PK its better to store as a binary field.
Do you have any thoughts about that? Here's a couple of links...

https://www.percona.com/blog/2014/12/19/store-uuid-optimized-way/

http://stackoverflow.com/questions/2365132/uuid-performance-in-mysql/2365176

regards

l.

**Comment by alsofronie** [comment]
Hi,

You can store it as binary, but I need to figure out how to make it primary key. Unfortunately, the `Scheme` object from Laravel has no length argument on binary (it's just a blob). MySQL and other PDO enabled db systems are aware of `binary` length. [Here is the issue on Laravel](https://github.com/laravel/framework/issues/1606).

The problem is, when you create the primary key, you **need** to specify the length.
An alternative will be to specify the field not as primary key but as index (uuid is guaranteed to be unique) so there is no problem there.

**Comment by londoh** [comment]
thanks for reply with good points.

I wasnt aware of that laravel issue, but taylor gives a solution - is that workable?

Anyway I appreciate this isnt really an 'issue' as such here, and may not be important to you. I was just searching saw your new package and thought to open a discussion. 
close as you see fit.

regards

l.

**Comment by alsofronie** [comment]
I also need this functionality... I'll leave it open for now :100:

**Comment by alsofronie** [comment]
fixed
