### ISSUE TITLE
Get uuid of newly created model

### ISSUE THREAD

**Issue by timvdalen** [alsofronie/eloquent-uuid#2]
How do you get the uuid of a newly created model?
The uuid is saved to the database correctly, but isn't being set on the returned model and reloading from the database doesn't work because the keys don't match.

**Comment by alsofronie** [comment]
It's just in tests (I expect there's something with the sqlite :memory: setup in the tests), in the real application everything is working normally.

I'll verify this again.
Thanks.

**Comment by timvdalen** [comment]
This is in an actual application with a MySQL backend

**Comment by alsofronie** [comment]
This is a trait (well, three of them) to be used in an actual application with a PDO-enabled backend.
As you can see, there is no "laravel/laravel" requirement in composer.json so no, **this is not an actual application**.

**Comment by timvdalen** [comment]
I am using your trait in an actual application, and I'm experiencing the behaviour I described in the OP.
I'll give it a try with the newest version, e668397c96a53fb6ffdf5c136d1efbf5228eebcb might have fixed this.

**Comment by alsofronie** [comment]
Yes, it's fixed :) The only thing you should worry about is, in your migrations, to use DB::statement(...) to create the actual binary(16) field with primary key attached, as you have no option in table Blueprint.

For example:
**The migration file**

``` php
    Schema::create('users', function(Blueprint $table) {
        // $table->increments('id'); // this must go if you're using binary
        $table->string('email');
        $table->string('password');
        $table->timestamps();
    });

    // this must be added in order to make a binary uuid primary key -- mysql version
    DB::statement('ALTER TABLE users ADD COLUMN id BINARY(16) PRIMARY KEY');
```

The problem is we do not have a `$table->binary('id',16)->primary()`, we only have `$table->binary('id')->primary()` and MySQL (at least) is complaining it cannot have any index on a column with unknown size.

**Comment by alsofronie** [comment]
There is a `$table->uuid('id')` which makes a `CHAR(36)` but obviously you cannot use it to store a binary uuid in an optimised way.
