### ISSUE TITLE
v1.0.8 Breaks custom attribute on model/More memory required

### ISSUE THREAD

**Issue by JValck** [alsofronie/eloquent-uuid#32]
Although the new release seems to fix the serialization problem (#29), setting a temporarily custom attribute with default PHP syntax is no longer possible.

Unit test:
```
public function testToArray(){
	$model = EloquentBinOptimizedUserModel::create([
            'username' => 'Model',
       	    'password' => 'secret'
       	]);
	$customModel = EloquentBinOptimizedPostModel::create(['name' => 'bla']);
	$model->cust = $customModel;
		
	$array = $model->toArray();
	static::assertNotNull($array);

	$json = json_encode($array);
	var_dump($json);
	static::assertNotNull($json);

}
```

The test above passes in v1.0.7, but the new version leads to more memory consumption resulting in:
``mmap() failed: [12] Cannot allocate memory``
causing the server to hang/crash.

**Comment by alsofronie** [comment]
Thanks. I did not know the `parent::toArray()` will not transform **everything** into arrays. I think the `method_exists` is slow (the current fix), but this is the only method I can think of to keep the traits and not moving to interfaces. Testing for the class name (which I think it's slightly faster) will introduce an additional `if` because Laravel moved from `Eloquent` in 5.2 to `Model` in 5.3 and I would like to keep the 5.1 - 5.4 compatibility.

It seems though my original trait approach, used for speed, is no longer a viable option. I think there will be a `Contract` / `Interface` based package (v2) that will replace this for new installs.

**Comment by JValck** [comment]
The binary UUID's are causing all the problems, but looking at the database it's a better option than using strings. As you propose interfaces could make the code cleaner.

However, yesterday I noticed that there is still an issue with the new implementation of the ```deepArray```-method. When the ```$value``` field is not a string or an object, an infinite loop will occur. I solved this issue and will open a PR.
